name = "AeronauticsSMP"
author = "Glorpie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c6266f83114ea4b65432b327a3ec6d15a84e3853a9c4a60f022f0b6f77ffb74"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
