name = "AeronauticsSMP"
author = "Glorpie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2def827f93d570e8c768116a9a33ce1fb84c79b8e412d8ca7de94f0b888fd3d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
