name = "AeronauticsSMP"
author = "Glorpie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8346df1bff90c0dad21b30a3169188b4e04e8dc2f1eab2e78a16c4ee9c2b4fae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
